name: Build and Run

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v1

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/${{github.event.repository.name}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/${{github.event.repository.name}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/${{github.event.repository.name}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Run
        working-directory: ${{runner.workspace}}/${{github.event.repository.name}}/build
        run: ./program3

      - name: Archive Inner Join Results
        uses: actions/upload-artifact@v1
        with:
          name: Result
          path: Results.csv